import test from 'node:test';
import assert from 'node:assert/strict';
import { Game, TASKS, EXPLANATIONS } from '../game.js';
function setup(n=5){let now=100000;const g=new Game(()=>now);const first=g.create('Alex',n);const sessions=[first];for(let i=1;i<n;i++)sessions.push(g.join(first.code,'Colleague '+i));for(const s of sessions){g.connect(s.token);g.action(s.token,'ready');}g.action(first.token,'start');const r=g.rooms.get(first.code);return {g,r,sessions,setTime:n=>now=n,staff:()=>r.players.filter(p=>p.faction==='staff'),ops:()=>r.players.filter(p=>p.faction==='operative')};}
function unanimous(g,r,target){g.phase(r,'vote');for(const p of g.voters(r))g.action(p.token,'vote',{target:p.id===target?null:target});g.advance(r);}
test('5–10 players get the correct faction count, unique jobs, and filtered private data',()=>{for(let n=5;n<=10;n++){const {g,r,ops}=setup(n);assert.equal(ops().length,n<=6?1:n<=9?2:3);assert.equal(new Set(r.players.map(p=>p.designation)).size,n);for(const p of r.players){const v=g.view(p.token);assert.equal(v.me.faction,p.faction);for(const other of v.players){assert.equal(other.faction,undefined);assert.equal(other.token,undefined);assert.equal(other.tasks,undefined);}assert.equal(v.votes,undefined);assert.equal(v.events,undefined);assert.ok(v.me.tasks.every(t=>t.answer===undefined));}}});
test('room bounds, names, host control, and readiness are enforced',()=>{const g=new Game();assert.throws(()=>g.create('A',4));assert.throws(()=>g.create('',5));assert.throws(()=>g.create('a'.repeat(25),5));const a=g.create('Host',5);g.connect(a.token);assert.throws(()=>g.action(a.token,'start'));const b=g.join(a.code,'Other');g.connect(b.token);assert.throws(()=>g.action(b.token,'start'));assert.throws(()=>g.join('WRONG','Other'));});
test('task answers are validated once and only during work',()=>{const {g,r,staff}=setup();const p=staff()[0],t=p.tasks[0];assert.throws(()=>g.action(p.token,'task',{id:t.id,answer:TASKS[t.type].answer}));g.advance(r);assert.throws(()=>g.action(p.token,'task',{id:t.id,answer:[99]}));g.action(p.token,'task',{id:t.id,answer:TASKS[t.type].answer});assert.equal(r.progress,4);assert.equal(p.completed,1);assert.throws(()=>g.action(p.token,'task',{id:t.id,answer:TASKS[t.type].answer}));assert.throws(()=>g.action(staff()[1].token,'task',{id:t.id,answer:TASKS[t.type].answer}));});
test('sabotage is faction-gated, once per round, and clues do not reveal actor IDs',()=>{const {g,r,ops,staff}=setup();g.advance(r);assert.throws(()=>g.action(staff()[0].token,'sabotage',{action:'Move the File'}));g.action(ops()[0].token,'sabotage',{action:'Move the File'});assert.ok(r.fileMissing);assert.throws(()=>g.action(ops()[0].token,'sabotage',{action:'Delay the Report'}));assert.deepEqual(g.view(staff()[0].token).clues,[]);g.action(staff()[0].token,'restore');assert.equal(r.fileMissing,false);g.advance(r);assert.ok(g.view(staff()[0].token).clues.length);assert.equal(g.view(staff()[0].token).clues[0].actorId,undefined);});
test('a correct majority eliminates an operative, promotes voters, and ends in staff victory',()=>{const {g,r,ops,staff}=setup();const op=ops()[0];unanimous(g,r,op.id);assert.equal(op.alive,false);assert.equal(r.ending,'staff');assert.equal(r.phase,'ended');for(const p of staff()){assert.equal(p.rank,1);assert.equal(p.influence,1);assert.equal(p.correctVotes,1);}});
test('plurality, ties, and abstentions do not cause penalties; ballots remain private',()=>{const {g,r}=setup(6);g.phase(r,'vote');const ps=r.players;g.action(ps[0].token,'vote',{target:ps[5].id});g.action(ps[1].token,'vote',{target:ps[5].id});g.action(ps[2].token,'vote',{target:ps[4].id});g.action(ps[3].token,'vote',{target:ps[4].id});g.action(ps[4].token,'vote',{target:null});assert.throws(()=>g.action(ps[0].token,'vote',{target:null}));assert.equal(g.view(ps[1].token).result,null);g.advance(r);assert.equal(r.phase,'resolution');assert.ok(ps.every(p=>p.lives===2));assert.equal(r.result.ballots.length,6);});
test('accepted appeal preserves lives and is only usable once',()=>{const {g,r,staff}=setup();const p=staff()[0];unanimous(g,r,p.id);assert.equal(r.phase,'appeal');g.action(p.token,'appeal',{text:EXPLANATIONS[0]});for(const other of r.players.filter(x=>x!==p))g.action(other.token,'appealVote',{accept:true});assert.throws(()=>g.action(p.token,'appealVote',{accept:true}));g.advance(r);assert.equal(p.lives,2);assert.ok(p.appealUsed);g.day(r);unanimous(g,r,p.id);assert.equal(p.lives,1);assert.equal(r.phase,'resolution');});
test('rejected appeal and subsequent wrong accusation eliminate innocent staff',()=>{const {g,r,staff}=setup();const p=staff()[0];unanimous(g,r,p.id);g.action(p.token,'appeal',{text:EXPLANATIONS[1]});for(const other of r.players.filter(x=>x!==p))g.action(other.token,'appealVote',{accept:false});g.advance(r);assert.equal(p.lives,1);g.day(r);unanimous(g,r,p.id);assert.equal(p.lives,0);assert.equal(p.alive,false);assert.equal(g.view(p.token).me.faction,null);assert.deepEqual(g.view(p.token).me.tasks,[]);g.phase(r,'meeting');assert.throws(()=>g.action(p.token,'chat',{text:'I was working on the shared project.'}));});
test('two-player ending takes precedence over a staff victory',()=>{const {g,r}=setup();for(const p of r.players.slice(0,3))p.alive=false;r.players[3].faction='staff';r.players[4].faction='staff';assert.equal(g.checkEnd(r),true);assert.equal(r.ending,'politics');assert.equal(r.deadline,null);});
test('reconnect restores identity and one-shot actions; grace expiry removes voters',()=>{const {g,r,ops,setTime}=setup();g.advance(r);const p=ops()[0];g.action(p.token,'sabotage',{action:'Delay the Report'});g.disconnect(p.token);setTime(110000);g.connect(p.token);assert.equal(g.view(p.token).me.id,p.id);assert.ok(g.view(p.token).me.actionUsed);g.disconnect(p.token);setTime(140001);g.tick();assert.equal(p.alive,false);assert.ok(!g.voters(r).includes(p));});
test('timers advance on server and stale submissions are rejected',()=>{const {g,r,setTime}=setup();setTime(r.deadline);g.tick();assert.equal(r.phase,'work');setTime(r.deadline);const p=r.players[0],t=p.tasks[0];assert.throws(()=>g.action(p.token,'task',{id:t.id,answer:TASKS[t.type].answer}));g.tick();assert.equal(r.phase,'incident');const deadline=r.deadline;g.tick();assert.equal(r.deadline,deadline);});
test('influence produces bounded evidence without exposing identities and works once',()=>{const {g,r,staff}=setup(7);const p=staff()[0];p.influence=2;g.phase(r,'incident');g.action(p.token,'influence');assert.equal(p.influence,1);assert.equal(r.clues.length,1);assert.throws(()=>g.action(p.token,'influence'));});
test('disconnects abandon a match with fewer than three active players',()=>{const {g,r,setTime}=setup();for(const p of r.players.slice(0,3))g.disconnect(p.token);setTime(130001);g.tick();assert.equal(r.ending,'abandoned');});
test('rematch clears role, task, appeal, and promotion state',()=>{const {g,r}=setup();g.finish(r,'staff');g.action(r.players[0].token,'rematch');assert.equal(r.phase,'lobby');assert.ok(r.players.every(p=>p.faction===null&&!p.ready&&p.lives===2&&p.alive&&!p.appealUsed));});
